version: "3.7"

services:
  postgres:
    image: postgres:14
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  hasura:
    image: hasura/graphql-engine:v2.3.0.cli-migrations-v3
    ports:
      - "8080:8080"
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,http-log,query-log,webhook-log,websocket-log
      HASURA_GRAPHQL_ADMIN_SECRET: hasura
      ACTIONS_BASE_URL: http://actions:3000

  actions:
    image: hasura-actions
    build: ./actions
    ports:
      - "3000"

volumes:
  db_data: